name: zartech
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.0
  dio: ^4.0.4
  flutter_search_bar: ^2.1.0
  auto_route: ^3.2.3
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  flutter_neumorphic: ^3.0.3
  google_sign_in: ^5.2.1
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  http: ^0.13.4
  json_annotation: 4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mocktail: ^0.2.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

dependency_overrides:
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Light.ttf
        - asset: fonts/Gilroy-Medium.ttf
        - asset: fonts/Gilroy-Medium.ttf

  assets:
    - assets/images/logo_white.png
    - assets/images/google_logo.png
    - assets/images/ic_veg.png
    - assets/images/ic_menu.png
    - assets/images/ic_cart.png
    - assets/images/ic_non_veg.png
